name: edufriends_global
description: Dream,Learn,Explore.

publish_to: 'none'

version: 3.0.0+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  carousel_slider: 5.0.0
  lucide_icons: ^0.257.0
  collection: 1.19.1
  file_picker: 8.1.2
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  flutter_native_splash: 2.4.1
  flutter_plugin_android_lifecycle: 2.0.20
  font_awesome_flutter: 10.7.0
  flutter_svg: ^2.0.7
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.2.1
  intl: 0.20.2
  json_path: 0.7.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  plugin_platform_interface: 2.1.8
  pointer_interceptor: 0.10.1+2
  pointer_interceptor_ios: 0.10.1
  pointer_interceptor_platform_interface: 0.10.0+1
  pointer_interceptor_web: 0.10.2+1
  provider: 6.1.2
  shared_preferences: 2.3.2
  shared_preferences_android: 2.3.2
  shared_preferences_foundation: 2.5.2
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.2
  shared_preferences_windows: 2.4.1
  sqflite: 2.3.3+1
  sqflite_common: 2.5.4+3
  timeago: 3.7.1
  universal_io: 2.2.2
  url_launcher: 6.3.0
  url_launcher_android: 6.3.10
  url_launcher_ios: 6.3.1
  url_launcher_linux: 3.2.0
  url_launcher_macos: 3.2.1
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.3.3
  url_launcher_windows: 3.1.2
  uuid: ^4.0.0
  webview_flutter: 4.9.0
  webview_flutter_android: 3.16.7
  webview_flutter_platform_interface: 2.10.0
  webview_flutter_wkwebview: 3.15.0
  webviewx_plus: 0.5.0
  xml: 6.5.0
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.2
  pointer_interceptor: 0.10.1+2
  pointer_interceptor_ios: 0.10.1
  pointer_interceptor_platform_interface: 0.10.0+1
  pointer_interceptor_web: 0.10.2+1
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: 4.2.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: false
  ios: false
  web:
    generate: true
    image_path: "web/icons/app_launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/countries/
    - assets/images/flags/
    - assets/images/brand/
    - assets/images/brand/edufriends_logo_light.svg
    - assets/images/brand/edufriends_logo_dark.svg
    - assets/images/brand/edufriends_mark.svg
    - assets/images/brand/edufriends_mark.png
    - assets/images/onboarding/onboarding_1.png
    - assets/images/onboarding/onboarding_2.png
    - assets/images/onboarding/onboarding_3.png
    - assets/images/brand/edufriends_mark.png
    - assets/images/brand/edufriends_mark_dark.svg
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
